// login de usuario
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const CERRAR_SESION = 'CERRAR_SESION';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// barra de herramientas
export const HERRAMIENTAS_PRECIOS = 'HERRAMIENTAS_PRECIOS';
export const HERRAMIENTAS_STOCK_PRODUCTO = 'HERRAMIENTAS_STOCK_PRODUCTO';
export const HERRAMIENTAS_STOCK_PTO_STOCK = 'HERRAMIENTAS_STOCK_PTO_STOCK';
export const HERRAMIENTAS_STOCK_MOVIMIENTOS = 'HERRAMIENTAS_STOCK_MOVIMIENTOS';
export const HERRAMIENTAS_NUEVA_VENTA = 'HERRAMIENTAS_NUEVA_VENTA';
export const BUSQUEDA_ACTUAL = 'BUSQUEDA_ACTUAL';
export const BUSQUEDA_ACTUAL_CLIENTE = 'BUSQUEDA_ACTUAL_CLIENTE';
export const PTOS_STOCK = 'PTOS_STOCK';
export const LISTAS_PRECIO = 'LISTAS_PRECIO';
export const ERROR_BARRA_HERRAMIENTAS = 'ERROR_BARRA_HERRAMIENTAS';

// precios
export const TRAER_PRECIOS = 'TRAER_PRECIOS';
export const ERROR_PRECIOS = 'ERROR_PRECIOS';
export const LISTA_PRECIOS = 'LISTA_PRECIOS';
export const FILAS_PRECIOS = 'FILAS_PRECIOS';

// stock
export const TRAER_STOCK_TOTAL = 'TRAER_STOCK_TOTAL';
export const TRAER_STOCK_PTO_STOCK = 'TRAER_STOCK_PTO_STOCK';
export const TRAER_MOVIMIENTOS_STOCK = 'TRAER_MOVIMIENTOS_STOCK';
export const FILAS_STOCK_TOTAL = 'FILAS_STOCK_TOTAL';
export const FILAS_PTO_STOCK = 'FILAS_PTO_STOCK';
export const FILAS_MOVIMIENTOS_STOCK = 'FILAS_MOVIMIENTOS_STOCK';
export const PTO_STOCK = 'PTO_STOCK';
export const PRODUCTO_ACTIVO = 'PRODUCTO_ACTIVO';
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const ERROR_STOCK = 'ERROR_STOCK';
export const ACTIVAR_FILA = 'ACTIVAR_FILA';
export const CONFIRMAR_CAMBIO_STOCK = 'CONFIRMAR_CAMBIO_STOCK';
export const CONFIRMAR_CAMBIO_STOCK_PTO_STOCK =
	'CONFIRMAR_CAMBIO_STOCK_PTO_STOCK';
export const NUEVA_CANTIDAD_STOCK = 'NUEVA_CANTIDAD_STOCK';

// ventas
export const PTO_STOCK_VENTAS = 'PTO_STOCK_VENTAS';
export const PTOS_STOCK_VENTAS = 'PTOS_STOCK_VENTAS';
export const LISTA_PRECIO_VENTAS = 'LISTA_PRECIO_VENTAS';
export const VALOR_RADIO_VENTAS = 'VALOR_RADIO_VENTAS';
export const CARRITO_AGREGAR_PRODUCTO = 'CARRITO_AGREGAR_PRODUCTO';
export const CARRITO_QUITAR_PRODUCTO = 'CARRITO_QUITAR_PRODUCTO';
export const CARRITO_MODIFICAR_CANTIDAD = 'CARRITO_MODIFICAR_CANTIDAD';
export const CARRITO_MODIFICAR_PRECIO = 'CARRITO_MODIFICAR_PRECIO';
export const PRODUCTOS_VENTAS = 'PRODUCTOS_VENTAS';
export const FILAS_VENTAS = 'FILAS_VENTAS';
export const LIMPIAR_CARRITO = 'LIMPIAR_CARRITO';
export const MODO_CARGA_VENTA = 'MODO_CARGA_VENTA';
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';
export const AGREGAR_ENVIO = 'AGREGAR_ENVIO';
export const LIMPIAR_CLIENTE = 'LIMPIAR_CLIENTE';
export const AGREGAR_NOTA = 'AGREGAR_NOTA';
export const AGREGAR_ORDEN_ECOMMERCE = 'AGREGAR_ORDEN_ECOMMERCE';
export const PTOS_VENTA = 'PTOS_VENTA';
export const PTO_VENTA = 'PTO_VENTA';
export const TIPOS_ENVIO = 'TIPOS_ENVIO';
export const CREAR_ORDEN = 'CREAR_ORDEN';
export const TRAER_ORDENES = 'TRAER_ORDENES';
export const HERRAMIENTAS_EDITAR_VENTAS = 'HERRAMIENTAS_EDITAR_VENTAS';
export const FILAS_ORDENES = 'FILAS_ORDENES';
export const FILAS_ORDENES_FILTRO = 'FILAS_ORDENES_FILTRO';

// clientes
export const TRAER_CLIENTES = 'TRAER_CLIENTES';
export const FILAS_CLIENTES = 'FILAS_CLIENTES';
export const CAMPO_CLIENTE_ACTIVO = 'CAMPO_CLIENTE_ACTIVO';
export const LIMPIAR_CLIENTE_ACTIVO = 'LIMPIAR_CLIENTE_ACTIVO';
export const MOSTRAR_ERROR = 'MOSTRAR_ERROR';
export const OPEN_INFORMACION_CLIENTE = 'OPEN_INFORMACION_CLIENTE';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
